### ISSUE TITLE
Option to work transparently with Netlify Cache

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy-cache-assets#3]
Look at this API! https://twitter.com/philhawksworth/status/1257284661874692097

**Comment by aarongustafson** [comment]
What are you thinking? Config option in global Eleventy to override `options.directory` (since the Netlify cache plugin defaults to `_cache`)?

**Comment by zachleat** [comment]
Docs are building for this: https://www.11ty.dev/docs/plugins/cache/#running-this-on-your-build-server
